server:
  port: 8080
  servlet:
    context-path: /challenge-service

spring:
  cloud:
    config:
      enabled: false
      
  redis:
# in case of execution of this projects with docker compose, uncomment line below if commented  
    host: 'challenge-eventstore_redis_1'
# in case of execution of this projects with an IDE, uncomment line below if commented  
#    host: 'localhost'
    database: 1
# In this case, i preferred to use Lettuce because this is an scalable and thread safe client for redis    
    lettuce: 
    
# Here, i use a connection pool for multithreading and reusing connections, in addition to ensure thread safe (This object is thread safe)    
      pool:
        max-active: 32
        max-idle: 2
        min-idle: 1

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  endpoint:
    metrics:
      enabled: false
